language: python
python:
- '3.6'
before_script:
- yes | python setup.py install
- git clone https://github.com/uc-cdis/dictionaryutils; cd dictionaryutils
script:
- "./run_tests.sh"
deploy:
  provider: s3
  access_key_id: AKIAZRNPHKJIAJDGWKPS
  secret_access_key:
    secure: pieIECcLlWwA/mmOfH6nvRYW9UnjN9o5I+N3/mNkcApgWH02+QK1MyFo4uhb4H/r6sNKW36E7Po3H8RSGSYiZjscmsS3p/qq+9B9nlgLYjiFUUAVWd9YKYSXKXSUZCUa+9nGGKymb16ONeVFpkEV2gEdwFTmEKEHV/xMfNvoA2vqWBiLPGhFSyAyo8MhUw+HbPkc3Qyf24uJkQIa8m987I4FLykZ0/9o12lk+7aPxE+2faoYQuUpPALzxCpuqYXQjd/ZweFY4k70/KKd2gXDdlwrFxsBlAGDLv0u0Ig+00WHkXwYG+6h1/O420EKX3KgHW42hwSNFJcH6KwrWV1OVWgRBGmvjE8tZyzi/9fs5J6Odd3jXwZBmz3hqJAawZb/OOgji3KY0j57FKVKvIbM4bGcRoL6EUbjIZBjxCjPXK4AiyGKr3snJB3q8v5Cz6C0GrdOznB06LPW1ckV1BFC6Wk780wbwR1Dh+U1rK6VoJA1Psk7K4QpZX3F2OWPxTAXs3SJfmJI9CxA6uvOmBYe6RKkmY5WJY6O7gGtt1b5ay3ANt1GjM27eOzCy06X/QtEsxnerJll8lItL9yoLYF0mHCmTMQCfyoRoxV2nXPaAyvpUXp/zQYAiK6uWTSDIWvQJvjzPwCLlJyjh5Zcot62kX7VDNoJongfhx19y9m+WA8=
  bucket: dictionary-artifacts
  local-dir: artifacts
  upload-dir: tcga_dictionary/$TRAVIS_BRANCH
  skip_cleanup: true
  on:
    repo: uc-cdis/tcga_dictionary
    all_branches: true
